apiVersion: metallb.io/v1beta1
kind: MetalLB
metadata:
  name: metallb
  namespace: metallb-system
spec:
  addressPools:
    - name: default-pool
      protocol: layer2
      addresses:
        - 192.168.0.151-192.168.0.151
